export interface WanItem {
  IPv4Enable: boolean
  IPv4AddrType: string
  IPv4Addr: string
  IPv4Mask: string
  IPv4StaticDnsServers: string
  IPv4Gateway: string
  DownBandwidthMax: number
  IPv4DnsServers: string
  APN: string
  DNSOverrideAllowed: boolean
  IPv6Enable: boolean
  IPv4StaticAddr: string
  IPv6AddrType: string
  UpBandwidthHistory: string
  IPv6Addr: string
  accessAuthEnable: boolean
  LowerLayer: string
  IsConfigured: number
  IPv6DnsServers: string
  accessDevNum: number
  IPv6PrefixList: string
  DownBandwidthHistory: string
  WANDHCPOption60: string
  IPv4StaticMask: string
  UpBandwidthMax: number
  IPv4StaticGateway: string
  IsDefault: number
  UpBandwidth: number
  MACColone: string
  DownBandwidth: number
  MACColoneEnable: boolean
  IPv6Gateway: string
  IPv6AddrPrefixLen: number
  X_SpeDialMode: number
  Username: string
  WanType: string
  MRU: number
  IPv6AddrSet: string
  PPPDialIpAddr: string
  Password: string
  PPPTrigger: string
  PPPDialIpMode: string
  PPPIdletime: number
  Name: string
  PPPoEServiceName: string
  Alias: string
  Enable: boolean
  AccessType: string
  BandwidthTime: string
  ConnectionType: string
  ConnectionStatus: string
  IPv6ConnectionStatus: string
  ServiceList: string
  AccessStatus: string
  PPPAuthMode: string
  MTU: number
  DialNum: string
  MSS: number
  ID: string
  NATType: number
}

export type Wan = WanItem[]
